# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLUiG737BJIYj60CpOzUAB3rO9RCP_8o
"""

R1 = float(input("Enter R1 value: "))
R2 = float(input("Enter R2 value: "))

total = R1 + R2

p1 = R1 / total
p2 = R2 / total
print("\n total=",total)
print("p1 =", p1)
print("P1 Percentage =",p1*100,"%")
print("p2 =", p2)
print("P2 Percentage =",p2*100,"%")
print("p1 + p2 =", p1 + p2)

def is_safe(vertex, color, graph, colors):
    """Check whether assigning 'color' to vertex is safe."""
    for neighbor in range(len(graph)):
        if graph[vertex][neighbor] == 1 and colors[neighbor] == color:
            return False
    return True


def graph_coloring_util(vertex, graph, num_colors, colors):
    """Backtracking function to color the graph."""
    n = len(graph)

    # All vertices are colored
    if vertex == n:
        return True

    # Try every color
    for color in range(1, num_colors + 1):
        if is_safe(vertex, color, graph, colors):
            colors[vertex] = color

            if graph_coloring_util(vertex + 1, graph, num_colors, colors):
                return True

            # Backtrack
            colors[vertex] = 0

    return False


def minimum_coloring(graph):
    """Find the minimum number of colors needed."""
    n = len(graph)

    # Try 1, 2, 3, ... colors
    for num_colors in range(1, n + 1):
        colors = [0] * n

        if graph_coloring_util(0, graph, num_colors, colors):
            return num_colors, colors

    return n, colors



def is_safe(vertex, color, graph, colors):
    """Check whether assigning 'color' to vertex is safe."""
    for neighbor in range(len(graph)):
        if graph[vertex][neighbor] == 1 and colors[neighbor] == color:
            return False
    return True


def graph_coloring_util(vertex, graph, num_colors, colors):
    """Backtracking function to color the graph."""
    n = len(graph)

    # All vertices are colored
    if vertex == n:
        return True

    # Try every color
    for color in range(1, num_colors + 1):
        if is_safe(vertex, color, graph, colors):
            colors[vertex] = color

            if graph_coloring_util(vertex + 1, graph, num_colors, colors):
                return True

            # Backtrack
            colors[vertex] = 0

    return False


def minimum_coloring(graph):
    """Find the minimum number of colors needed."""
    n = len(graph)

    # Try 1, 2, 3, ... colors
    for num_colors in range(1, n + 1):
        colors = [0] * n

        if graph_coloring_util(0, graph, num_colors, colors):
            return num_colors, colors

    return n, colors

def is_safe(vertex, color, graph, colors):
    """Check whether assigning 'color' to vertex is safe."""
    for neighbor in range(len(graph)):
        if graph[vertex][neighbor] == 1 and colors[neighbor] == color:
            return False
    return True


def graph_coloring_util(vertex, graph, num_colors, colors):
    """Backtracking function to color the graph."""
    n = len(graph)

    # All vertices are colored
    if vertex == n:
        return True

    # Try every color
    for color in range(1, num_colors + 1):
        if is_safe(vertex, color, graph, colors):
            colors[vertex] = color

            if graph_coloring_util(vertex + 1, graph, num_colors, colors):
                return True

            # Backtrack
            colors[vertex] = 0

    return False


def minimum_coloring(graph):
    """Find the minimum number of colors needed."""
    n = len(graph)

    # Try 1, 2, 3, ... colors
    for num_colors in range(1, n + 1):
        colors = [0] * n

        if graph_coloring_util(0, graph, num_colors, colors):
            return num_colors, colors

    return n, colors